# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/AMD_Vivado/Vivado_Projects/AES_Encryption/AES_Encryption.srcs/sources_1/bd/AXI_AES_test/ip/AXI_AES_test_processing_system7_0_1/AXI_AES_test_processing_system7_0_1.xci
# IP: The module: 'AXI_AES_test_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/AMD_Vivado/Vivado_Projects/AES_Encryption/AES_Encryption.gen/sources_1/bd/AXI_AES_test/ip/AXI_AES_test_processing_system7_0_1/AXI_AES_test_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_AES_test_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/AMD_Vivado/Vivado_Projects/AES_Encryption/AES_Encryption.srcs/sources_1/bd/AXI_AES_test/ip/AXI_AES_test_processing_system7_0_1/AXI_AES_test_processing_system7_0_1.xci
# IP: The module: 'AXI_AES_test_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/AMD_Vivado/Vivado_Projects/AES_Encryption/AES_Encryption.gen/sources_1/bd/AXI_AES_test/ip/AXI_AES_test_processing_system7_0_1/AXI_AES_test_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_AES_test_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
